INSERT into tech_skills (id, name)  VALUES(1, "Java");
INSERT INTO tech_skills (id, name) VALUES (2, "Python");
INSERT INTO tech_skills (id, name) VALUES (3, "JavaScript");
INSERT INTO tech_skills (id, name) VALUES (4, "C++");
INSERT INTO tech_skills (id, name) VALUES (5, "Ruby");
INSERT INTO tech_skills (id, name) VALUES (6, "PHP");
INSERT INTO tech_skills (id, name) VALUES (7, "Swift");
INSERT INTO tech_skills (id, name) VALUES (8, "Kotlin");
INSERT INTO tech_skills (id, name) VALUES (9, "C#");
INSERT INTO tech_skills (id, name) VALUES (10, "SQL");
INSERT INTO tech_skills (id, name) VALUES (11, "HTML");
INSERT INTO tech_skills (id, name) VALUES (12, "CSS");
INSERT INTO tech_skills (id, name) VALUES (13, "React");
INSERT INTO tech_skills (id, name) VALUES (14, "Angular");
INSERT INTO tech_skills (id, name) VALUES (15, "Vue.js");
INSERT INTO tech_skills (id, name) VALUES (16, "Docker");
INSERT INTO tech_skills (id, name) VALUES (17, "Kubernetes");
INSERT INTO tech_skills (id, name) VALUES (18, "AWS");
INSERT INTO tech_skills (id, name) VALUES (19, "Azure");
INSERT INTO tech_skills (id, name) VALUES (20, "Git");
INSERT INTO tech_skills (id, name) VALUES (21, "Jenkins");
INSERT INTO tech_skills (id, name) VALUES (22, "Terraform");
INSERT INTO tech_skills (id, name) VALUES (23, "Spring Framework");
INSERT INTO tech_skills (id, name) VALUES (24, "Ruby on Rails");
INSERT INTO soft_skills (name) VALUES ('Mentalidad de crecimiento');
INSERT INTO soft_skills (name) VALUES ('Orientacion al futuro');
INSERT INTO soft_skills (name) VALUES ('Orientacion al detalle');
INSERT INTO soft_skills (name) VALUES ('Comunicacion');
INSERT INTO soft_skills (name) VALUES ('Responsabilidad Personal');
INSERT INTO soft_skills (name) VALUES ('Persistencia');
INSERT INTO soft_skills (name) VALUES ('Proactividad');
INSERT INTO soft_skills (name) VALUES ('Trabajo en equipo');