INSERT into tech_skills (name)  VALUES ('Java');
INSERT INTO tech_skills (name) VALUES ('Python');
INSERT INTO tech_skills (name) VALUES ('JavaScript');
INSERT INTO tech_skills (name) VALUES ('C++');
INSERT INTO tech_skills (name) VALUES ('Ruby');
INSERT INTO tech_skills (name) VALUES ('PHP');
INSERT INTO tech_skills (name) VALUES ('Swift');
INSERT INTO tech_skills (name) VALUES ('Kotlin');
INSERT INTO tech_skills (name) VALUES ('C#');
INSERT INTO tech_skills (name) VALUES ('SQL');
INSERT INTO tech_skills (name) VALUES ('HTML');
INSERT INTO tech_skills (name) VALUES ('CSS');
INSERT INTO tech_skills (name) VALUES ('React');
INSERT INTO tech_skills (name) VALUES ('Angular');
INSERT INTO tech_skills (name) VALUES ('Vue.js');
INSERT INTO tech_skills (name) VALUES ('Docker');
INSERT INTO tech_skills (name) VALUES ('Kubernetes');
INSERT INTO tech_skills (name) VALUES ('AWS');
INSERT INTO tech_skills (name) VALUES ('Azure');
INSERT INTO tech_skills (name) VALUES ('Git');
INSERT INTO tech_skills (name) VALUES ('Jenkins');
INSERT INTO tech_skills (name) VALUES ('Terraform');
INSERT INTO tech_skills (name) VALUES ('Spring Framework');
INSERT INTO tech_skills (name) VALUES ('Ruby on Rails');
INSERT INTO soft_skills (name) VALUES ('Mentalidad de crecimiento');
INSERT INTO soft_skills (name) VALUES ('Orientacion al futuro');
INSERT INTO soft_skills (name) VALUES ('Orientacion al detalle');
INSERT INTO soft_skills (name) VALUES ('Comunicacion');
INSERT INTO soft_skills (name) VALUES ('Responsabilidad Personal');
INSERT INTO soft_skills (name) VALUES ('Persistencia');
INSERT INTO soft_skills (name) VALUES ('Proactividad');
INSERT INTO soft_skills (name) VALUES ('Trabajo en equipo');